config/routes.rb
Rails.application.routes.draw do
  get 'places/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get    '/login', to: 'sessions#new'      #ログインページへ
  post   '/login', to: 'sessions#create'   #ログイン(セッション作成)
  delete '/logout', to: 'sessions#destroy' #ログアウト(セッション削除)
  
  get 'working_user', to: 'users#working_user'
  get 'working_user_osaka', to: 'users#working_user_osaka'
  get 'working_user_tokyo', to: 'users#working_user_tokyo'
  get 'working_user_nagoya', to: 'users#working_user_nagoya'
  
  get 'osaka', to: 'users#index_osaka'
  get 'tokyo', to: 'users#index_tokyo'
  get 'nagoya', to: 'users#index_nagoya'
  
  get 'request/users', to: 'attendances#request_users'
  get 'approval/users', to: 'attendances#approval_users'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update do
      member do
        patch 'update_request'
        patch 'update_approval'
        delete 'cancel_request'
        delete 'cancel_approval'
      end
    end
  end
  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  validates :work_place_of_user, presence: true
  validates :employment_status, presence: true
  validates :occupation, presence: true
  has_secure_password
  validates :password, length: { maximum: 10 }, allow_nil: true
  
  validate :work_time_than_basic_time
  
  def work_time_than_basic_time
      errors.add(:basic_time, "より多い指定勤務時間は無効です") if work_time > basic_time
  end
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_token, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search) 
    if search
      where(['name LIKE ?', "%#{search}%"]) 
    else
      all 
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  
  before_action :set_user, only: [:show, :destroy, :edit, :update, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:show, :index, :destroy, :edit, :update, :index_osaka, :index_tokyo, :index_nagoya,
                                        :working_user_osaka, :working_user_tokyo, :working_user_nagoya]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :working_user,
                                    :working_user_osaka, :working_user_tokyo, :working_user_nagoya]
  before_action :admin_or_correct_user, only: :show
  before_action :set_one_month, only: :show
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "新規作成に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def index
    @users = User.paginate(page: params[:page], per_page: 20).search(params[:search])
  end
  
  def index_osaka
    index_place("大阪")
  end
  
  def index_tokyo
    index_place("東京")
  end
  
  def index_nagoya
    index_place("名古屋")
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil, finished_at: nil).count
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を編集しました。"
      redirect_to @user
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      if User.update_all(basic_time: @user.basic_time, work_time: @user.work_time)
        flash[:success] = "基本情報を更新しました。"
      else
        flash[:danger] = "基本情報を更新できませんでした"
      end
    else
      flash[:danger] = "基本情報の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def working_user
    work
  end
  
  def working_user_osaka
    work
  end
  
  def working_user_tokyo
    work
  end
  
  def working_user_nagoya
    work
  end
    
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :department, :work_place_of_user, 
                                   :employment_status, :occupation, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:occupation, :employment_status, :basic_time, :work_time)
    end
    
    def admin_or_correct_user
      redirect_to root_url unless current_user.admin? || @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
   # 勤怠基本情報を指定のフォーマットで返す。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  def sunday_or_saturday_color(x)
    css_class = 
          case $days_of_the_week[x.worked_on.wday]
            when '土'
              'text-primary'
            when '日'
              'text-danger'
          end
    return css_class
  end
  
  def index_place(x)
    @users = User.where(work_place_of_user: x).paginate(page: params[:page], per_page: 20).search(params[:search])
  end
  
  def work
    @attendances = Attendance.where(finished_at: nil, worked_on: Date.current).where.not(started_at: nil, )
  end
  
  def request_users_num
    attendances = Attendance.where(worked_on: Date.current, overtime_request: "1", overtime_approval: nil)
    @num = attendances.count
  end
  
  def approval_users_num
    attendances = Attendance.where(worked_on: Date.current, overtime_approval: "1")
    @num = attendances.count
  end
  
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="text-center modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :employment_status, class: "label-#{yield(:class_text)}" %>
            <%= f.select :employment_status, {'正社員': "正社員", '契約社員': '契約社員',
                                        'アルバイト': 'アルバイト', '派遣社員': "派遣社員",
                                        'フリーランス': "フリーランス"},
             { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
      
            <%= f.label :occupation, class: "label-#{yield(:class_text)}" %>
            <%= f.select :occupation, {'エンジニア': "エンジニア", '事務員': '事務員',},
            { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit "更新", class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-basic-info" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
    
      <%= f.label :name, class: "label-user--edit" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, class: "label-user--edit" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :work_place_of_user, class: "label-user--edit" %>
      <%= f.select :work_place_of_user, {'大阪': "大阪", '東京': '東京', '名古屋': '名古屋'}, 
      { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>

      <%= f.label :employment_status, class: "label-user--edit" %>
      <%= f.select :employment_status, {'正社員': "正社員", '契約社員': '契約社員',
                                        'アルバイト': 'アルバイト', '派遣社員': "派遣社員",
                                        'フリーランス': "フリーランス"},
      { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
      
      <%= f.label :occupation, class: "label-user--edit" %>
      <%= f.select :occupation, {'エンジニア': "エンジニア", '事務員': '事務員',},
      { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
      
      <%= f.label :password, class: "label-user--edit}" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, class: "label-user--edit" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-user--edit" %>
<% end %>

app/views/users/_index_place.html.erb
<h1 class = "text-center">
  <% if params[:search] %>
    検索結果
  <% else %>
    <%= yield(:place) %>の社員一覧
  <% end %>
</h1>
 
<%= form_tag(osaka_path, :method => 'get', class: "pull-right") do %>
  <p class = "label-search">社員検索</p>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil, class: "btn btn-sm btn-primary pull-right btn-search" %>
<% end %> 

<h1><%= link_to "全社員一覧", users_path, class: "btn btn-big btn-danger" %></h1>

<div class = "col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class = "table table-condensed table-hover" id = "table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th><%= User.human_attribute_name :occupation %></th>
        <th><%= User.human_attribute_name :employment_status %></th>
        <th><%= User.human_attribute_name :basic_time %></th>
        <th><%= User.human_attribute_name :work_time %></th>
        <th><%= User.human_attribute_name :work_place_of_user %></th>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.occupation %></td>
        <td><%= user.employment_status %></td>
        <td><%= format_basic_info(user.basic_time) %></td>
        <td><%= format_basic_info(user.work_time) %></td>
        <td><%= user.work_place_of_user %></td>
        <td>
          <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" %>
          <% unless current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/_work.html.erb
<div>
<%= link_to "全拠点の出勤従業員一覧", working_user_path, class: "btn btn-danger btn-place" %>
<%= link_to "大阪本社の出勤者一覧", working_user_osaka_path, class: "btn btn-success btn-place btn-place" %>
<%= link_to "東京支社の出勤者一覧", working_user_tokyo_path, class: "btn btn-warning btn-place btn-place" %>
<%= link_to "名古屋支社の出勤者一覧", working_user_nagoya_path, class: "btn btn-info btn-place btn-place" %>
</div>

<h1 class="text-center"><%= yield(:place) %>従業員一覧</h1>

<table class="table table-striped table-bordered table-work">
  <thead>
    <tr>
      <th>名前</th>
      <th><%= User.human_attribute_name :occupation %></th>
      <th><%= User.human_attribute_name :employment_status %></th>
      <th><%= User.human_attribute_name :work_place_of_user %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @attendances.each do |attendance| %>
      <% user = User.find(attendance.user_id) %>
        <tr>
          <% if user.work_place_of_user == yield(:place) %>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= user.occupation %></td>
            <td><%= user.employment_status %></td>
            <td><%= user.work_place_of_user %></td>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:button_text, '更新') %>
<h1 class = "text-center">アカウント情報の更新</h1>
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
      <%= render 'users/form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "Edit-Basic-Info") %>

<h1 class = "text-center">基本情報の更新</h1>
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
      <%= form_with(model: @user, url: update_basic_info_user_path, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
    
      <%= f.label :basic_time, class: "basic-info-label" %>
      <%= f.time_field :basic_time, class: "form-control" %>

      <%= f.label :work_time, class: "basic-info-label"  %>
      <%= f.time_field :work_time, class: "form-control" %>
      
      <%= f.submit "編集", class: "btn btn-primary btn-block btn-edit-basic" %>
      <% end %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, "従業員一覧") %>

<h1 class = "text-center">
  <% if params[:search] %>
    検索結果
  <% else %>
    従業員一覧
  <% end %>
</h1>
<div>
  <%= link_to "大阪本店の従業員一覧", osaka_path, class: "btn btn-success btn-place" %>
  <%= link_to "東京支店の従業員一覧", tokyo_path, class: "btn btn-warning btn-place" %>
  <%= link_to "名古屋支店の従業員一覧", nagoya_path, class: "btn btn-info btn-place" %>
</div>

<%= form_tag(users_path, :method => 'get', class: "pull-right") do %>
  <p class = "label-search">従業員検索</p>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil, class: "btn btn-sm btn-primary pull-right btn-search" %>
<% end %> 
<div class = "col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class = "table table-condensed table-hover" id = "table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th><%= User.human_attribute_name :occupation %></th>
        <th><%= User.human_attribute_name :employment_status %></th>
        <th><%= User.human_attribute_name :basic_time %></th>
        <th><%= User.human_attribute_name :work_time %></th>
        <th><%= User.human_attribute_name :work_place_of_user %></th>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.occupation %></td>
        <td><%= user.employment_status %></td>
        <td><%= format_basic_info(user.basic_time) %></td>
        <td><%= format_basic_info(user.work_time) %></td>
        <td><%= user.work_place_of_user %></td>
        <td>
          <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" %>
          <% unless current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/index_tokyo.html.erb
<% provide(:title, "東京従業員") %>

<h1 class = "text-center">
  <% if params[:search] %>
    検索結果
  <% else %>
    東京支店の従業員一覧
  <% end %>
</h1>
 
<%= form_tag(tokyo_path, :method => 'get', class: "pull-right") do %>
  <p class = "label-search">従業員検索</p>
  <%= text_field_tag :search %>
  <%= submit_tag '検索', :name => nil, class: "btn btn-sm btn-primary pull-right btn-search" %>
<% end %> 

<div>
　<%= link_to "大阪本社の従業員一覧", osaka_path, class: "btn btn-success btn-place" %>
  <%= link_to "東京支社の従業員一覧", tokyo_path, class: "btn btn-warning btn-place" %>
  <%= link_to "名古屋支社の従業員一覧", nagoya_path, class: "btn btn-info btn-place" %>
  <%= link_to "全従業員一覧", users_path, class: "btn btn-danger btn-place" %>
</div>

<div class = "col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class = "table table-condensed table-hover" id = "table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th><%= User.human_attribute_name :occupation %></th>
        <th><%= User.human_attribute_name :employment_status %></th>
        <th><%= User.human_attribute_name :basic_time %></th>
        <th><%= User.human_attribute_name :work_time %></th>
        <th><%= User.human_attribute_name :work_place_of_user %></th>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.occupation %></td>
        <td><%= user.employment_status %></td>
        <td><%= format_basic_info(user.basic_time) %></td>
        <td><%= format_basic_info(user.work_time) %></td>
        <td><%= user.work_place_of_user %></td>
        <td>
          <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" %>
          <% unless current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<div class = "text-center">
  <h1>従業員登録</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class = "table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "◀", user_path(date: @first_day.prev_month), class: "btn btn-primary btn-prev" %>
        <%= l(@first_day, format: :middle) %> 時間管理表
        <%= link_to "▶", user_path(date: @first_day.next_month), class: "btn btn-primary btn-next" %>
      </td>
      <td>指定勤務時間:　<%= format_basic_info(@user.work_time) %></td> 
      <td colspan = "2">基本時間:　<%= format_basic_info(@user.basic_time) %></td>
      <td>勤務形態:  <%= @user.employment_status %></td>
      <td >初日:　<%= l(@first_day, format: :short) %></td>
    </tr>
    
    <tr>
      <td>職種:　<%= @user.occupation %></td>
      <td>氏名:　<%= @user.name %></td>
      <td>勤務地</td>
      <td><%= @user.work_place_of_user %></td>
      <td>出勤日数:　<%= @worked_sum %>日</td>
      <td>締め:　<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class = "edit-user">
  <%= link_to "勤怠編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
</div>

<div>
  <table class = "table table-bordered table-condenced table-hover" id = "table-attendances">
    <thead>
      <tr>
        <th rowspan = "2">日付</th>
        <th rowspan = "2">曜日</th>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
        <th rowspan = "2"></th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class = "<%= sunday_or_saturday_color(day) %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= day.started_at.hour if day.started_at.present? %></td>
          <td><%= format_minute_quarter(day.started_at) if day.started_at.present? %></td>
          <td class = "text-center">
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-block btn-secondary btn-attendance" %>
            <% end %>
          </td>
          <td><%= day.finished_at.hour if day.finished_at.present? %></td>
          <td><%= format_minute_quarter(day.finished_at) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td>
            <%  unless @user.admin? %>
            <% if day.worked_on == Date.current && day.overtime_approval.nil? %>
              <% if day.overtime_request.nil? %>
                <%= link_to "残業申請", update_request_user_attendance_path(@user, day), method: :patch,
                  data: { confirm: "残業申請しますか？" },
                class: "btn btn-primary" %>
              <% else %>
                残業申請中です。<%= link_to "残業申請をキャンセル", cancel_request_user_attendance_path(@user, day), method: :delete,
                                data: { confirm: "残業申請をキャンセルしますか？" },
                                class: "btn btn-danger pull-right" %>
              <% end %>
            <% elsif day.worked_on == Date.current && day.overtime_approval == "1" %>
                残業は承認されました。
            <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td colspan = "2"></td>
        <td colspan = "6">合計勤務時間 : <%=  format("%.2f", @total_working_times.to_f)%></td>
        <td></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>

app/views/users/working_user.html.erb
<% provide(:title, "出勤従業員一覧") %>

<%= link_to "大阪本社の出勤者一覧", working_user_osaka_path, class: "btn btn-success btn-place btn-place" %>
<%= link_to "東京支社の出勤者一覧", working_user_tokyo_path, class: "btn btn-warning btn-place btn-place" %>
<%= link_to "名古屋支社の出勤者一覧", working_user_nagoya_path, class: "btn btn-info btn-place btn-place" %>

<table class="table table-striped table-bordered table-work">
  <thead>
    <tr>
      <th>出勤従業員一覧</th>
      <th><%= User.human_attribute_name :work_place_of_user %></th>
      <th><%= User.human_attribute_name :employment_status %></th>
      <th><%= User.human_attribute_name :work_place_of_user %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @attendances.each do |attendance| %>
    <tr>
      <% user = User.find(attendance.user_id) %>
      <td><%= link_to user.name, user_path(user.id) %></td>
      <td><%= user.occupation %></td>
      <td><%= user.employment_status %></td>
      <td><%= user.work_place_of_user %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/working_user_nagoya.html.erb
<% provide(:title, "名古屋出勤") %>
<% provide(:place, "名古屋支社") %>
<%= render 'users/work' %>

app/views/users/working_user_osaka.html.erb
<% provide(:title, "大阪出勤") %>
<% provide(:place, "大阪本社") %>
<%= render 'users/work' %>