config/routes.rb
Rails.application.routes.draw do
  get 'places/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get    '/login', to: 'sessions#new'      #ログインページへ
  post   '/login', to: 'sessions#create'   #ログイン(セッション作成)
  delete '/logout', to: 'sessions#destroy' #ログアウト(セッション削除)
  
  get 'working_user', to: 'users#working_user'
  get 'working_user_osaka', to: 'users#working_user_osaka'
  get 'working_user_tokyo', to: 'users#working_user_tokyo'
  get 'working_user_nagoya', to: 'users#working_user_nagoya'
  
  get 'osaka', to: 'users#index_osaka'
  get 'tokyo', to: 'users#index_tokyo'
  get 'nagoya', to: 'users#index_nagoya'
  
  get 'request/users', to: 'attendances#request_users'
  get 'approval/users', to: 'attendances#approval_users'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update do
      member do
        patch 'update_request'
        patch 'update_approval'
        delete 'cancel_request'
        delete 'cancel_approval'
      end
    end
  end
  
  
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  # before_save { self.started_at = started_at.strftime("%H:%M") }
  # before_save { self.finished_at = finished_at.strftime("%H:%M") }
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
   
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end 
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退社時刻は無効です") if started_at > finished_at
    end
  end
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  include AttendancesHelper
  
  before_action :set_user, only: [:edit_one_month, :update_one_month]
  before_action :logged_in_user
  before_action :admin_or_correct_user, except: [:update_request, :update_approval, :cancel_request, :request_users,
                                                 :approval_users, :update_approval, :cancel_approval, :request_users]
  before_action :admin_user, only: [:update_approval, :cancel_approval, :request_users, :approval_users]
  before_action :set_one_month, only: :edit_one_month
  before_action :set_overtime, only: [:update_request, :update_approval, :cancel_request, :cancel_approval]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "おつかれさまでした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      if attendances_invalid?
        attendances_params.each do |id, item|
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
        end
        flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
        redirect_to user_url(date: params[:date])
      else
        flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
        redirect_to attendances_edit_one_month_user_url(date: params[:date])
      end
    end
  rescue ActiveRecord::RecordInvalid
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  def request_users
    @attendances = Attendance.where(worked_on: Date.current, overtime_request: "1", overtime_approval: nil)
  end
  
  def update_request
    @attendance.update_attributes!(overtime_request: "1")
    flash[:success] = "管理者に残業申請しました。"
    redirect_to user_url(@user)
  end
  
  def approval_users
    @attendances = Attendance.where(worked_on: Date.current, overtime_approval: "1")
  end
  
  def update_approval
    @attendance.update_attributes!(overtime_approval: "1")
    @user = User.find(@attendance.user_id)
    flash[:success] = "#{@user.name}の残業申請を承認しました。"
    redirect_to @user
  end
  
  def cancel_request
    @attendance.update_attributes(overtime_request: nil)
    flash[:danger] = "残業申請をキャンセルしました。"
    redirect_to @user
  end
  
  def cancel_approval
    @attendance.update_attributes(overtime_request: nil, overtime_approval: nil)
    @user = User.find(@attendance.user_id)
    flash[:danger] = "#{@user.name}の残業承認を取り消しました。"
    redirect_to @user
  end
  
  private
  
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
    
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません"
        redirect_to(root_url)
      end
    end
    
    def set_overtime
      @user = User.find(params[:user_id])
      @attendance = Attendance.find(params[:id])
    end
    
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return "出社" if attendance.started_at.nil?
      return "退社" if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  def working_times(start, finish)
    s = start.hour.to_f + format_minute_quarter(start).to_f / 60
    f = finish.hour.to_f + format_minute_quarter(finish).to_f / 60
    format("%.2f", f - s)
  end
  
  def format_minute_quarter(time)
    format("%i", 15 * (time.min / 15))
  end
  
  def attendances_invalid?
    a = true
      attendances_params.each do |id, item|
        if item[:started_at].blank? && item[:finished_at].blank?
          next
        elsif item[:started_at].blank? || item[:finished_at].blank?
          a = false
          break
        end
      end
      return a
  end

end

app/views/attendances/approval_users.html.erb
<% provide(:title, "残業") %>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>名前</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
    <% @user = User.find(attendance.user_id) %>
      <tr>
        <td><%= link_to @user.name, @user %></td>
        <td>
          <%= link_to "残業承認を取り消す。", cancel_approval_user_attendance_path(@user, attendance), 
                    method: :delete,
                    data: { confirm: "許可した残業承認を取り消しますか？" },
                class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<div>
  <table class = "table table-bordered table-condencd table-hover" id = "attendances-edit">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出勤時間</th>
        <th>退勤時間</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]", day do |attendance| %>
          <% if day.worked_on <= Date.current %>
          <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td class = "<%= sunday_or_saturday_color(day) %>">
              <%= $days_of_the_week[day.worked_on.wday] %>
            </td>
            <td><%= attendance.time_field :started_at, class: "form-control" %></td>
            <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= working_times(day.started_at, day.finished_at) %>
              <% end %>
            </td>
            <td><%= attendance.text_field :note, class: "form-control" %></td>
          </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class = "text-center">
  <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default edit-one-month" %>
  <%= f.submit "編集を保存する", class: "btn btn-lg btn-default edit-one-month" %>
</div>
<% end %>

app/views/attendances/request_users.html.erb
<% provide(:title, "残業申請者") %>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>名前</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
    <% @user = User.find(attendance.user_id) %>
      <tr>
        <td><%= link_to @user.name, @user %></td>
        <td>
          <%= link_to "残業を許可します。", update_approval_user_attendance_path(@user, attendance), method: :patch,
                    data: { confirm: "残業を許可しますか？" },
                class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>