config/routes.rb
Rails.application.routes.draw do
  get 'places/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get    '/login', to: 'sessions#new'      #ログインページへ
  post   '/login', to: 'sessions#create'   #ログイン(セッション作成)
  delete '/logout', to: 'sessions#destroy' #ログアウト(セッション削除)
  
  get 'working_user', to: 'users#working_user'
  get 'working_user_osaka', to: 'users#working_user_osaka'
  get 'working_user_tokyo', to: 'users#working_user_tokyo'
  get 'working_user_nagoya', to: 'users#working_user_nagoya'
  
  get 'osaka', to: 'users#index_osaka'
  get 'tokyo', to: 'users#index_tokyo'
  get 'nagoya', to: 'users#index_nagoya'
  
  get 'request/users', to: 'attendances#request_users'
  get 'approval/users', to: 'attendances#approval_users'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update do
      member do
        patch 'update_request'
        patch 'update_approval'
        delete 'cancel_request'
        delete 'cancel_approval'
      end
    end
  end
  
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠管理web", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "トップへ", root_path %></li>
          <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "従業員一覧", users_path %></li>
            <li><%= link_to "出勤中従業員", working_user_path %></li>
            <li><%= link_to "基本情報の修正", edit_basic_info_user_path(current_user) %></li>
            <% request_users_num %>
            <% if @num >= 1 %>
              <li><%= link_to "残業申請者が#{@num}名います", request_users_path, class: "abc" %></li>
            <% end %>
            <% approval_users_num %>
            <% if @num >= 1 %>
              <li><%= link_to "残業承認者一覧", approval_users_path %></li>
            <% end %>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "勤怠", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, msg| %>
        <div class = "alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
    </div>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>